services:
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
            target: prod
            args:
                WWWUSER: ${WWWUSER}
                WWWGROUP: ${WWWGROUP}
        restart: always
        container_name: bangsal-app
        working_dir: /var/www
        volumes:
            - .:/var/www:cached
            - .docker/php/supervisord.conf:/etc/supervisord.conf
            - .docker/php/supervisor.conf:/etc/supervisor/conf.d/supervisor.conf
        depends_on:
            # - mysql
            - redis
        networks:
              - external_net 

    nginx:
        image: nginx:alpine
        container_name: bangsal-nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
              - external_net 

    # postgres:
    #     image: postgres:16-alpine
    #     container_name: bangsal-postgres
    #     restart: always
    #     environment:
    #         POSTGRES_DB: ${DB_DATABASE}
    #         POSTGRES_USER: ${DB_USERNAME}
    #         POSTGRES_PASSWORD: ${DB_PASSWORD}
    #     volumes:
    #         - pg_data:/var/lib/postgresql/data
    #     networks:
    #           - external_net 

    redis:
        image: redis:alpine
        container_name: bangsal-redis
        restart: always
        volumes:
            - redis_data:/data
        networks:
              - external_net 

volumes:
    # pg_data:
    redis_data:

networks:
  external_net :
    external: true
